name: Run eratosthenes sieve

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: /eratosthenes-sieve
      run: cargo build --verbose
    - name: Run
      working-directory: /eratosthenes-sieve
      run: cargo run --verbose
